/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package TestTicTacToe;

import java.awt.Color;

/**
 *
 * @author kenicia
 */
public class TicTacToeGUI extends javax.swing.JFrame {

    private String startGameText = "X";
    Color startGameColor = Color.RED;

    public TicTacToeGUI() {
        initComponents();
    }
    
    private void player() {
        if (startGameText.equalsIgnoreCase("X")) {
            startGameText = "O";
            startGameColor = Color.BLACK;
        } else {
            startGameText = "X";
            startGameColor = Color.RED;
        }
    }

    private void winner() {
        String x = "X";
        String o = "O";
        String b1 = btnLabel1.getText();
        String b2 = btnLabel2.getText();
        String b3 = btnLabel3.getText();
        String b4 = btnLabel4.getText();
        String b5 = btnLabel5.getText();
        String b6 = btnLabel6.getText();
        String b7 = btnLabel7.getText();
        String b8 = btnLabel8.getText();
        String b9 = btnLabel9.getText();

        if (b1 == b2 && b2 == b3 && b3 == o || b3 == x) {
            winnerLabel.setText(b1 + " wins!");
            topPanel.setBackground(Color.WHITE);
            btmPanel.setBackground(Color.WHITE);
        } else if (b4 == b5 && b5 == b6 && b6 == o || b6 == x) {
            winnerLabel.setText(b4 + " wins!");
            topPanel.setBackground(Color.WHITE);
            btmPanel.setBackground(Color.WHITE);
        } else if (b7 == b8 && b8 == b9 && b9 == o || b9 == x) {
            winnerLabel.setText(b7 + " wins!");
            topPanel.setBackground(Color.WHITE);
            btmPanel.setBackground(Color.WHITE);
        } else if (b1 == b4 && b4 == b7 && b7 == o || b7 == x) {
            winnerLabel.setText(b1 + " wins!");
            topPanel.setBackground(Color.WHITE);
            btmPanel.setBackground(Color.WHITE);
        } else if (b2 == b5 && b5 == b8 && b8 == o || b8 == x) {
            winnerLabel.setText(b2 + " wins!");
            topPanel.setBackground(Color.WHITE);
            btmPanel.setBackground(Color.WHITE);
        } else if (b3 == b6 && b6 == b9 && b9 == o || b9 == x) {
            winnerLabel.setText(b3 + " wins!");
            topPanel.setBackground(Color.WHITE);
            btmPanel.setBackground(Color.WHITE);
        } else if (b1 == b5 && b5 == b9 && b9 == o || b9 == x) {
            winnerLabel.setText(b1 + " wins!");
            topPanel.setBackground(Color.WHITE);
            btmPanel.setBackground(Color.WHITE);
        } else if (b3 == b5 && b5 == b7 && b7 == o || b7 == x) {
            winnerLabel.setText(b3 + " wins!");
            topPanel.setBackground(Color.WHITE);
            btmPanel.setBackground(Color.WHITE);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainPanel = new javax.swing.JPanel();
        playLabel = new javax.swing.JLabel();
        startLabel = new javax.swing.JLabel();
        gamePanel = new javax.swing.JPanel();
        btmPanel = new javax.swing.JPanel();
        btnLabel1 = new javax.swing.JLabel();
        btnLabel2 = new javax.swing.JLabel();
        btnLabel3 = new javax.swing.JLabel();
        btnLabel4 = new javax.swing.JLabel();
        btnLabel5 = new javax.swing.JLabel();
        btnLabel6 = new javax.swing.JLabel();
        btnLabel7 = new javax.swing.JLabel();
        btnLabel8 = new javax.swing.JLabel();
        btnLabel9 = new javax.swing.JLabel();
        newGameLabel = new javax.swing.JLabel();
        winnerLabel = new javax.swing.JLabel();
        topPanel = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Tic Tac Toe");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        mainPanel.setBackground(new java.awt.Color(0, 0, 0));
        mainPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        playLabel.setFont(new java.awt.Font("Noteworthy", 0, 48)); // NOI18N
        playLabel.setForeground(new java.awt.Color(204, 255, 204));
        playLabel.setText("Let's play Tic Tac Toe!");
        mainPanel.add(playLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 100, -1, -1));

        startLabel.setBackground(new java.awt.Color(255, 102, 102));
        startLabel.setFont(new java.awt.Font("Noteworthy", 0, 48)); // NOI18N
        startLabel.setForeground(new java.awt.Color(255, 255, 255));
        startLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        startLabel.setText("Start");
        startLabel.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        startLabel.setOpaque(true);
        startLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                startLabelMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                startLabelMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                startLabelMouseEntered(evt);
            }
        });
        mainPanel.add(startLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 210, 220, 110));

        getContentPane().add(mainPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 600, 420));

        gamePanel.setBackground(new java.awt.Color(153, 204, 255));
        gamePanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btmPanel.setBackground(new java.awt.Color(102, 153, 255));
        btmPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        gamePanel.add(btmPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 410, 600, 10));

        btnLabel1.setBackground(new java.awt.Color(153, 204, 0));
        btnLabel1.setFont(new java.awt.Font("Avenir Next", 1, 48)); // NOI18N
        btnLabel1.setForeground(new java.awt.Color(255, 255, 255));
        btnLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnLabel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2));
        btnLabel1.setOpaque(true);
        btnLabel1.setPreferredSize(new java.awt.Dimension(125, 125));
        btnLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnLabel1MouseClicked(evt);
            }
        });
        gamePanel.add(btnLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        btnLabel2.setBackground(new java.awt.Color(153, 204, 0));
        btnLabel2.setFont(new java.awt.Font("Avenir Next", 1, 48)); // NOI18N
        btnLabel2.setForeground(new java.awt.Color(255, 255, 255));
        btnLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnLabel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2));
        btnLabel2.setOpaque(true);
        btnLabel2.setPreferredSize(new java.awt.Dimension(125, 125));
        btnLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnLabel2MouseClicked(evt);
            }
        });
        gamePanel.add(btnLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 20, -1, -1));

        btnLabel3.setBackground(new java.awt.Color(153, 204, 0));
        btnLabel3.setFont(new java.awt.Font("Avenir Next", 1, 48)); // NOI18N
        btnLabel3.setForeground(new java.awt.Color(255, 255, 255));
        btnLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnLabel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2));
        btnLabel3.setOpaque(true);
        btnLabel3.setPreferredSize(new java.awt.Dimension(125, 125));
        btnLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnLabel3MouseClicked(evt);
            }
        });
        gamePanel.add(btnLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 20, -1, -1));

        btnLabel4.setBackground(new java.awt.Color(153, 204, 0));
        btnLabel4.setFont(new java.awt.Font("Avenir Next", 1, 48)); // NOI18N
        btnLabel4.setForeground(new java.awt.Color(255, 255, 255));
        btnLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnLabel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2));
        btnLabel4.setOpaque(true);
        btnLabel4.setPreferredSize(new java.awt.Dimension(125, 125));
        btnLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnLabel4MouseClicked(evt);
            }
        });
        gamePanel.add(btnLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, -1, -1));

        btnLabel5.setBackground(new java.awt.Color(153, 204, 0));
        btnLabel5.setFont(new java.awt.Font("Avenir Next", 1, 48)); // NOI18N
        btnLabel5.setForeground(new java.awt.Color(255, 255, 255));
        btnLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnLabel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2));
        btnLabel5.setOpaque(true);
        btnLabel5.setPreferredSize(new java.awt.Dimension(125, 125));
        btnLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnLabel5MouseClicked(evt);
            }
        });
        gamePanel.add(btnLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 150, -1, -1));

        btnLabel6.setBackground(new java.awt.Color(153, 204, 0));
        btnLabel6.setFont(new java.awt.Font("Avenir Next", 1, 48)); // NOI18N
        btnLabel6.setForeground(new java.awt.Color(255, 255, 255));
        btnLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnLabel6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2));
        btnLabel6.setOpaque(true);
        btnLabel6.setPreferredSize(new java.awt.Dimension(125, 125));
        btnLabel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnLabel6MouseClicked(evt);
            }
        });
        gamePanel.add(btnLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 150, -1, -1));

        btnLabel7.setBackground(new java.awt.Color(153, 204, 0));
        btnLabel7.setFont(new java.awt.Font("Avenir Next", 1, 48)); // NOI18N
        btnLabel7.setForeground(new java.awt.Color(255, 255, 255));
        btnLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnLabel7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2));
        btnLabel7.setOpaque(true);
        btnLabel7.setPreferredSize(new java.awt.Dimension(125, 125));
        btnLabel7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnLabel7MouseClicked(evt);
            }
        });
        gamePanel.add(btnLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 280, -1, -1));

        btnLabel8.setBackground(new java.awt.Color(153, 204, 0));
        btnLabel8.setFont(new java.awt.Font("Avenir Next", 1, 48)); // NOI18N
        btnLabel8.setForeground(new java.awt.Color(255, 255, 255));
        btnLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnLabel8.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2));
        btnLabel8.setOpaque(true);
        btnLabel8.setPreferredSize(new java.awt.Dimension(125, 125));
        btnLabel8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnLabel8MouseClicked(evt);
            }
        });
        gamePanel.add(btnLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 280, -1, -1));

        btnLabel9.setBackground(new java.awt.Color(153, 204, 0));
        btnLabel9.setFont(new java.awt.Font("Avenir Next", 1, 48)); // NOI18N
        btnLabel9.setForeground(new java.awt.Color(255, 255, 255));
        btnLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnLabel9.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2));
        btnLabel9.setOpaque(true);
        btnLabel9.setPreferredSize(new java.awt.Dimension(125, 125));
        btnLabel9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnLabel9MouseClicked(evt);
            }
        });
        gamePanel.add(btnLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 280, -1, -1));

        newGameLabel.setBackground(new java.awt.Color(255, 51, 51));
        newGameLabel.setFont(new java.awt.Font("Avenir Next Condensed", 1, 18)); // NOI18N
        newGameLabel.setForeground(new java.awt.Color(255, 255, 255));
        newGameLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        newGameLabel.setText("New Game");
        newGameLabel.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        newGameLabel.setOpaque(true);
        newGameLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                newGameLabelMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                newGameLabelMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                newGameLabelMouseEntered(evt);
            }
        });
        gamePanel.add(newGameLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 370, 100, 30));

        winnerLabel.setBackground(new java.awt.Color(204, 204, 255));
        winnerLabel.setFont(new java.awt.Font("Avenir Next", 1, 44)); // NOI18N
        winnerLabel.setForeground(new java.awt.Color(51, 51, 255));
        winnerLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        winnerLabel.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        winnerLabel.setOpaque(true);
        gamePanel.add(winnerLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 180, 170, 70));

        topPanel.setBackground(new java.awt.Color(102, 153, 255));
        topPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        gamePanel.add(topPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 600, 10));

        getContentPane().add(gamePanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 600, 420));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void startLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_startLabelMouseClicked
        // TODO add your handling code here:
        mainPanel.setVisible(false);
        gamePanel.setVisible(true);
        winnerLabel.setText(null);
        btnLabel1.setText(null);
        btnLabel2.setText(null);
        btnLabel3.setText(null);
        btnLabel4.setText(null);
        btnLabel5.setText(null);
        btnLabel6.setText(null);
        btnLabel7.setText(null);
        btnLabel8.setText(null);
        btnLabel9.setText(null);
    }//GEN-LAST:event_startLabelMouseClicked

    private void newGameLabelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_newGameLabelMouseEntered
        // TODO add your handling code here:
        newGameLabel.setBackground(Color.white);
        newGameLabel.setForeground(Color.red);
    }//GEN-LAST:event_newGameLabelMouseEntered

    private void newGameLabelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_newGameLabelMouseExited
        // TODO add your handling code here:
        newGameLabel.setBackground(new java.awt.Color(255, 51, 51));
        newGameLabel.setForeground(Color.white);

    }//GEN-LAST:event_newGameLabelMouseExited

    private void newGameLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_newGameLabelMouseClicked
        // TODO add your handling code here:
        gamePanel.setVisible(false);
        mainPanel.setVisible(true);
        winnerLabel.setText(null);
        btnLabel1.setText(null);
        btnLabel2.setText(null);
        btnLabel3.setText(null);
        btnLabel4.setText(null);
        btnLabel5.setText(null);
        btnLabel6.setText(null);
        btnLabel7.setText(null);
        btnLabel8.setText(null);
        btnLabel9.setText(null);
        btnLabel1.setBackground(new java.awt.Color(153, 204, 0));
        btnLabel2.setBackground(new java.awt.Color(153, 204, 0));
        btnLabel3.setBackground(new java.awt.Color(153, 204, 0));
        btnLabel4.setBackground(new java.awt.Color(153, 204, 0));
        btnLabel5.setBackground(new java.awt.Color(153, 204, 0));
        btnLabel6.setBackground(new java.awt.Color(153, 204, 0));
        btnLabel7.setBackground(new java.awt.Color(153, 204, 0));
        btnLabel8.setBackground(new java.awt.Color(153, 204, 0));
        btnLabel9.setBackground(new java.awt.Color(153, 204, 0));
        startGameText = "X";
        startGameColor = Color.RED;

    }//GEN-LAST:event_newGameLabelMouseClicked

    private void startLabelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_startLabelMouseEntered
        // TODO add your handling code here:
        startLabel.setBackground(Color.white);
        startLabel.setForeground(new java.awt.Color(255, 102, 102));
    }//GEN-LAST:event_startLabelMouseEntered

    private void startLabelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_startLabelMouseExited
        // TODO add your handling code here:
        startLabel.setForeground(Color.white);
        startLabel.setBackground(new java.awt.Color(255, 102, 102));
    }//GEN-LAST:event_startLabelMouseExited

    private void btnLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLabel1MouseClicked
        // TODO add your handling code here:
        btnLabel1.setText(startGameText);
        btnLabel1.setBackground(startGameColor);
        player();
        winner();
    }//GEN-LAST:event_btnLabel1MouseClicked

    private void btnLabel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLabel4MouseClicked
        // TODO add your handling code here:
        btnLabel4.setText(startGameText);
        btnLabel4.setBackground(startGameColor);
        player();
        winner();
    }//GEN-LAST:event_btnLabel4MouseClicked

    private void btnLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLabel2MouseClicked
        // TODO add your handling code here:
        btnLabel2.setText(startGameText);
        btnLabel2.setBackground(startGameColor);
        player();
        winner();
    }//GEN-LAST:event_btnLabel2MouseClicked

    private void btnLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLabel3MouseClicked
        // TODO add your handling code here:
        btnLabel3.setText(startGameText);
        btnLabel3.setBackground(startGameColor);
        player();
        winner();
    }//GEN-LAST:event_btnLabel3MouseClicked

    private void btnLabel5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLabel5MouseClicked
        // TODO add your handling code here:
        btnLabel5.setText(startGameText);
        btnLabel5.setBackground(startGameColor);
        player();
        winner();
    }//GEN-LAST:event_btnLabel5MouseClicked

    private void btnLabel6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLabel6MouseClicked
        // TODO add your handling code here:
        btnLabel6.setText(startGameText);
        btnLabel6.setBackground(startGameColor);
        player();
        winner();
    }//GEN-LAST:event_btnLabel6MouseClicked

    private void btnLabel7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLabel7MouseClicked
        // TODO add your handling code here:
        btnLabel7.setText(startGameText);
        btnLabel7.setBackground(startGameColor);
        player();
        winner();
    }//GEN-LAST:event_btnLabel7MouseClicked

    private void btnLabel8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLabel8MouseClicked
        // TODO add your handling code here:
        btnLabel8.setText(startGameText);
        btnLabel8.setBackground(startGameColor);
        player();
        winner();
    }//GEN-LAST:event_btnLabel8MouseClicked

    private void btnLabel9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLabel9MouseClicked
        // TODO add your handling code here:
        btnLabel9.setText(startGameText);
        btnLabel9.setBackground(startGameColor);
        player();
        winner();
    }//GEN-LAST:event_btnLabel9MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TicTacToeGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TicTacToeGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TicTacToeGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TicTacToeGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new TicTacToeGUI().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel btmPanel;
    private javax.swing.JLabel btnLabel1;
    private javax.swing.JLabel btnLabel2;
    private javax.swing.JLabel btnLabel3;
    private javax.swing.JLabel btnLabel4;
    private javax.swing.JLabel btnLabel5;
    private javax.swing.JLabel btnLabel6;
    private javax.swing.JLabel btnLabel7;
    private javax.swing.JLabel btnLabel8;
    private javax.swing.JLabel btnLabel9;
    private javax.swing.JPanel gamePanel;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JLabel newGameLabel;
    private javax.swing.JLabel playLabel;
    private javax.swing.JLabel startLabel;
    private javax.swing.JPanel topPanel;
    private javax.swing.JLabel winnerLabel;
    // End of variables declaration//GEN-END:variables
}
